from datetime import datetime

class PolicyTemplates:
    """
    SOVEREIGN POLICY TEMPLATES (V9.9)
    
    Contains structure and linguistic patterns for generating 
    high-level government briefings (Director General / Minister Level).
    
    """
    
    @staticmethod
    def get_header(sector="NATIONAL"):
        return {
            "title": f"AEGIS INTELLIGENCE BRIEF // {sector}",
            "classification": "CONFIDENTIAL // INTERNAL USE ONLY",
            "date": datetime.now().strftime("%d %B %Y"),
            "prepared_by": "SENTINEL PRIME AI (Autonomous Core)"
        }

    @staticmethod
    def get_executive_summary_template(risk_level, total_vol, ghost_savings):
        """
        Dynamic text generation for the 'Executive Summary' section.
        """
        
        tone = "neutral"
        if risk_level == "CRITICAL": tone = "urgent"
        
        text = f"""
        1. STRATEGIC OVERVIEW
        ---------------------
        The Sentinel Prime system has conducted a real-time audit of the Aadhaar enrolment 
        ecosystem. Current threat posture is assessed as {risk_level}. 
        
        Total transactional volume stands at {total_vol:,} updates/enrolments for the period. 
        Advanced forensic scanning has identified potential fiscal leakages amounting to 
        approximately ₹{ghost_savings} Crores via Ghost Beneficiary elimination.
        
        """
        
        if tone == "urgent":
            text += "\n*** ACTION REQUIRED: Immediate administrative intervention is recommended in flagged districts. ***\n"
            
        return text

    @staticmethod
    def get_fiscal_impact_section(savings, roi, fraud_prevented):
        return f"""
        2. FISCAL EFFICIENCY & ROI ANALYSIS
        -----------------------------------
        > PROJECTED SAVINGS: ₹{savings} Cr (Annualized)
        > KIT DEPLOYMENT ROI: {roi}% Efficiency Gain
        > FRAUD PREVENTION VALUE: ₹{fraud_prevented} Cr
        
        The deployment of Physics-Informed Kit re-balancing is projected to optimize 
        operational expenditure (OpEx) while maximizing saturation velocity in 
        under-served Digital Dark Zones.
        """

    @staticmethod
    def get_inclusion_section(dark_zones_count, demographics_flag):
        return f"""
        3. INCLUSION & EXCLUSION RISKS
        ------------------------------
        > DIGITAL DARK ZONES DETECTED: {dark_zones_count} Clusters
        > DEMOGRAPHIC SKEW: {demographics_flag}
        
        Spatial analysis indicates specific micro-regions where enrolment centers 
        are statistically inaccessible to vulnerable populations (Age > 60, Infants). 
        Immediate mobile van deployment is advised for these geofences.
        """

    @staticmethod
    def get_recommendation_matrix(action_items):
        """
        Formats a list of actions into a formal matrix.
        """
        formatted_actions = "\n".join([f"   [ ] {item}" for item in action_items])
        
        return f"""
        4. STRATEGIC RECOMMENDATIONS (AI-GENERATED)
        -------------------------------------------
        Based on Causal Inference models, the following actions are prioritized:
        
{formatted_actions}
        
        Failure to act on High-Priority items may result in a 15-20% increase in 
        authentication failures over the next quarter.
        """

    @staticmethod
    def get_footer():
        return """
        ______________________________________________________________________
        Generated by Sentinel Prime V9.9 | Physics-Informed Sovereign AI
        This document contains algorithmic predictions and should be validated 
        by field officers before final policy notification.
        """